version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password10
      POSTGRES_USER: root
      POSTGRES_DB: vestbank
    ports:
      - 5432:5432
    networks:
      - vest_network

  nginx:
    container_name: server-proxy
    build: ./proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - vest_network

  api:
    build: .
    ports:
      - 6200:6200
    environment:
      PORT: 6200
      TOKEN_SECRET: abcdef
      POSTGRES_USER: root
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: vestbank
      POSTGRES_PASSWORD: password10
      POSTGRES_PORT: 5434
    depends_on:
      - postgres
    networks:
      - vest_network

networks:
  vest_network:
